name: airtunnel_dns
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
